---
- name: Install IPTV analyzer on localhost
  hosts: databaseserver
  gather_facts: true
  vars:
    - show_debug: false
  tasks:
    - name: Run role to install database 
      include_role:
        name: bsmeding.iptv_analyzer
      vars:
        iptv_analyzer_install_database: true
        iptv_analyzer_database_install_frontend: true
        iptv_analyzer_install_collector: false

- name: Install IPTV analyzer on localhost
  hosts: collectors
  gather_facts: true
  vars:
    - show_debug: false
  tasks:        
    - name: Run role to install collector
      include_role:
        name: bsmeding.iptv_analyzer
      vars:
        iptv_analyzer_install_database: false
        iptv_analyzer_database_install_frontend: false
        iptv_analyzer_install_collector: true

